[package]
name = "lyra"
version = "0.1.0"
authors = ["Denis Memmesheimer <denismemmesheimer@gmail.com>"]
edition = "2018"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["secrets", "tls", "json", "msgpack"] }
#"uuid"
epos = { path = "../epos" }
